/**
 * Core interfaces for the Context Generation system.
 * Defines the data structures used across all pipeline stages.
 */

/** Result of validating a topic or use case description. */
export interface ValidationResult {
  valid: boolean;
  error?: string;
}

/** A question generated by the ClarificationAgent to refine the topic scope. */
export interface ClarificationQuestion {
  id: string;
  text: string;
  /** Why this question helps refine the topic. */
  purpose: string;
}

/** The refined topic scope produced after clarification. */
export interface TopicScope {
  originalTopic: string;
  originalUseCase: string;
  refinements: string[];
  summary: string;
}

/** The planned structure of a context set. */
export interface ContentPlan {
  files: PlannedFile[];
  estimatedTotal: number;
}

/** A single file planned for generation. */
export interface PlannedFile {
  subtopic: string;
  filename: string;
  description: string;
  /** Filenames this file should cross-reference. */
  relatedFiles: string[];
}

/** A generated context file with its content and metadata. */
export interface GeneratedFile {
  filename: string;
  title: string;
  content: string;
  crossReferences: CrossReference[];
}

/** A cross-reference link to another file in the context set. */
export interface CrossReference {
  targetFilename: string;
  anchorText: string;
}

/** Result of a file write or removal operation. */
export interface WriteResult {
  success: boolean;
  error?: string;
  path?: string;
}

/** Result of a file removal operation. */
export interface RemoveResult {
  success: boolean;
  error?: string;
}

/** Holds the accumulated state for a single context generation request. */
export interface GenerationSession {
  topicDescription: string;
  useCaseDescription: string;
  scope: TopicScope;
  plan: ContentPlan;
  generatedFiles: GeneratedFile[];
  outputDir: string;
}
